name: Run checks
on:
  pull_request:
  push:
    branches: [main]
jobs:
  checks:
    name: Nix checks
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-24.11
      - run: nix flake check
